# Generated by Django 2.1.1 on 2018-10-17 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['date'], 'verbose_name_plural': 'Budgets'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 9, 42, 43, 167980)),
        ),
        migrations.AlterModelTable(
            name='budget',
            table='budgets',
        ),
    ]
