# Generated by Django 2.1.1 on 2018-10-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('payed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='asset.Account')),
            ],
            options={
                'verbose_name_plural': 'Incomes',
                'db_table': 'incomes',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='asset.Account')),
                ('category', models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='asset.Category')),
            ],
            options={
                'verbose_name_plural': 'Outcomes',
                'db_table': 'outcomes',
                'ordering': ['date'],
            },
        ),
    ]
