# Generated by Django 2.1.1 on 2018-10-11 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=8)),
                ('from_account', models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='asset.Account')),
                ('to_account', models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='asset.Account')),
            ],
            options={
                'verbose_name_plural': 'Transfers',
                'db_table': 'transfers',
                'ordering': ['date'],
            },
        ),
    ]
