# Generated by Django 2.1.1 on 2018-10-17 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20181017_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 9, 30, 31, 284466)),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 9, 30, 31, 284830)),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 9, 30, 31, 285209)),
        ),
    ]
