# Generated by Django 2.1.1 on 2018-10-17 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_auto_20181017_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 9, 42, 43, 166662)),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 9, 42, 43, 167025)),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 9, 42, 43, 167402)),
        ),
    ]
